<?php

namespace App\DHL;

class Util
{
    static function getServiceNameByProductCode(string $code)
    {
        return static::$codes[$code]['name'];
    }

    static function getServiceTokenByProductCode(string $code)
    {
        return static::$codes[$code]['token'];
    }

    static function getProductCodeByServiceToken(string $token)
    {
        foreach (static::$codes as $code => $value) {
            if ($value['token'] === $token)
                return $code;
        }

        return '';
    }

    static function getServiceTokens()
    {
        $tokens = [];
        foreach (static::$codes as $key => $value) {
            $tokens[] = $value['token'];
        }

        return $tokens;
    }

    static function getCountryName(string $code)
    {
        return static::$countries[$code] ?: '';
    }

    static function getExportReasonCode(string $purpose)
    {
        return static::$reason_codes[$purpose] ?: 'P';
    }

    static $codes = [
        '0' => ['name' => 'LOGISTICS SERVICES', 'token' => 'dhl_express_log'],
        '1' => ['name' => 'DOMESTIC EXPRESS 12:00', 'token' => 'dhl_express_dot'],
        // '2' => ['name' => 'Placeholder code', 'token' => 'dhl_express_des'],
        '3' => ['name' => 'EXPRESS CHOICE', 'token' => 'dhl_express_2cp'],
        '4' => ['name' => 'SAMEDAY JETLINE', 'token' => 'dhl_express_nfo'],
        '5' => ['name' => 'SAMEDAY SPRINTLINE', 'token' => 'dhl_express_spl'],
        '6' => ['name' => 'AIR CAPACITY SALES', 'token' => 'dhl_express_acs'],
        '7' => ['name' => 'EXPRESS EASY', 'token' => 'dhl_express_xed'],
        '8' => ['name' => 'EXPRESS EASY', 'token' => 'dhl_express_xep'],
        '9' => ['name' => 'PARCEL PRODUCT', 'token' => 'dhl_express_ppd'],
        'A' => ['name' => 'ACCOUNTING', 'token' => 'dhl_express_n/a'],
        'B' => ['name' => 'BREAKBULK EXPRESS', 'token' => 'dhl_express_bbx'],
        'C' => ['name' => 'MEDICAL EXPRESS', 'token' => 'dhl_express_cmx'],
        'D' => ['name' => 'EXPRESS WORLDWIDE', 'token' => 'dhl_express_dox'],
        'E' => ['name' => 'EXPRESS 9:00', 'token' => 'dhl_express_tde'],
        'F' => ['name' => 'FREIGHT WORLDWIDE', 'token' => 'dhl_express_frt'],
        'G' => ['name' => 'ECONOMY SELECT DOMESTIC', 'token' => 'dhl_express_des'],
        'H' => ['name' => 'ECONOMY SELECT', 'token' => 'dhl_express_esi'],
        'I' => ['name' => 'EXPRESS DOMESTIC 9:00', 'token' => 'dhl_express_dok'],
        // 'J' => ['name' => 'EXPRESS JUMBO', 'token' => 'dhl_express_wpx'],
        'K' => ['name' => 'EXPRESS 9:00', 'token' => 'dhl_express_tdk'],
        'L' => ['name' => 'EXPRESS 10:30', 'token' => 'dhl_express_tdl'],
        'M' => ['name' => 'EXPRESS 10:30', 'token' => 'dhl_express_tdm'],
        'N' => ['name' => 'EXPRESS DOMESTIC', 'token' => 'dhl_express_dom'],
        'O' => ['name' => 'EXPRESS DOMESTIC 10:30', 'token' => 'dhl_express_dol'],
        'P' => ['name' => 'EXPRESS WORLDWIDE', 'token' => 'dhl_express_wpx'],
        'Q' => ['name' => 'MEDICAL EXPRESS', 'token' => 'dhl_express_wmx'],
        'R' => ['name' => 'GLOBAL MAIL', 'token' => 'dhl_express_gmb'],
        'S' => ['name' => 'SAME DAY', 'token' => 'dhl_express_sdx'],
        'T' => ['name' => 'EXPRESS 12:00', 'token' => 'dhl_express_tdt'],
        'U' => ['name' => 'EXPRESS WORLDWIDE', 'token' => 'dhl_express_ecx'],
        'V' => ['name' => 'PARCEL PRODUCT', 'token' => 'dhl_express_ppp'],
        'W' => ['name' => 'ECONOMY SELECT', 'token' => 'dhl_express_esu'],
        'X' => ['name' => 'EXPRESS ENVELOPE', 'token' => 'dhl_express_xpd'],
        'Y' => ['name' => 'EXPRESS 12:00', 'token' => 'dhl_express_tdy'],
        'Z' => ['name' => 'Duties & Taxes', 'token' => 'dhl_express_dtc'],
    ];

    static $countries = [
        'AD' => 'ANDORRA',
        'AE' => 'UNITED ARAB EMIRATES',
        'AF' => 'AFGHANISTAN',
        'AG' => 'ANTIGUA',
        'AI' => 'ANGUILLA',
        'AL' => 'ALBANIA',
        'AM' => 'ARMENIA',
        'AO' => 'ANGOLA',
        'AR' => 'ARGENTINA',
        'AS' => 'AMERICAN SAMOA',
        'AT' => 'AUSTRIA',
        'AU' => 'AUSTRALIA',
        'AW' => 'ARUBA',
        'AZ' => 'AZERBAIJAN',
        'BA' => 'BOSNIA AND HERZEGOVINA',
        'BB' => 'BARBADOS',
        'BD' => 'BANGLADESH',
        'BE' => 'BELGIUM',
        'BF' => 'BURKINA FASO',
        'BG' => 'BULGARIA',
        'BH' => 'BAHRAIN',
        'BI' => 'BURUNDI',
        'BJ' => 'BENIN',
        'BM' => 'BERMUDA',
        'BN' => 'BRUNEI',
        'BO' => 'BOLIVIA',
        'BR' => 'BRAZIL',
        'BS' => 'BAHAMAS',
        'BT' => 'BHUTAN',
        'BW' => 'BOTSWANA',
        'BY' => 'BELARUS',
        'BZ' => 'BELIZE',
        'CA' => 'CANADA',
        'CD' => 'CONGO, THE DEMOCRATIC REPUBLIC OF',
        'CF' => 'CENTRAL AFRICAN REPUBLIC',
        'CG' => 'CONGO',
        'CH' => 'SWITZERLAND',
        'CI' => 'COTE D IVOIRE',
        'CK' => 'COOK ISLANDS',
        'CL' => 'CHILE',
        'CM' => 'CAMEROON',
        'CN' => 'CHINA, PEOPLES REPUBLIC',
        'CO' => 'COLOMBIA',
        'CR' => 'COSTA RICA',
        'CU' => 'CUBA',
        'CV' => 'CAPE VERDE',
        'CY' => 'CYPRUS',
        'CZ' => 'CZECH REPUBLIC, THE',
        'DE' => 'GERMANY',
        'DJ' => 'DJIBOUTI',
        'DK' => 'DENMARK',
        'DM' => 'DOMINICA',
        'DO' => 'DOMINICAN REPUBLIC',
        'DZ' => 'ALGERIA',
        'EC' => 'ECUADOR',
        'EE' => 'ESTONIA',
        'EG' => 'EGYPT',
        'ER' => 'ERITREA',
        'ES' => 'SPAIN',
        'ET' => 'ETHIOPIA',
        'FI' => 'FINLAND',
        'FJ' => 'FIJI',
        'FK' => 'FALKLAND ISLANDS',
        'FM' => 'MICRONESIA, FEDERATED STATES OF',
        'FO' => 'FAROE ISLANDS',
        'FR' => 'FRANCE',
        'GA' => 'GABON',
        'GB' => 'UNITED KINGDOM',
        'GD' => 'GRENADA',
        'GE' => 'GEORGIA',
        'GF' => 'FRENCH GUYANA',
        'GG' => 'GUERNSEY',
        'GH' => 'GHANA',
        'GI' => 'GIBRALTAR',
        'GL' => 'GREENLAND',
        'GM' => 'GAMBIA',
        'GN' => 'GUINEA REPUBLIC',
        'GP' => 'GUADELOUPE',
        'GQ' => 'GUINEA-EQUATORIAL',
        'GR' => 'GREECE',
        'GT' => 'GUATEMALA',
        'GU' => 'GUAM',
        'GW' => 'GUINEA-BISSAU',
        'GY' => 'GUYANA (BRITISH)',
        'HK' => 'HONG KONG',
        'HN' => 'HONDURAS',
        'HR' => 'CROATIA',
        'HT' => 'HAITI',
        'HU' => 'HUNGARY',
        'IC' => 'CANARY ISLANDS, THE',
        'ID' => 'INDONESIA',
        'IE' => 'IRELAND, REPUBLIC OF',
        'IL' => 'ISRAEL',
        'IN' => 'INDIA',
        'IQ' => 'IRAQ',
        'IR' => 'IRAN (ISLAMIC REPUBLIC OF)',
        'IS' => 'ICELAND',
        'IT' => 'ITALY',
        'JE' => 'JERSEY',
        'JM' => 'JAMAICA',
        'JO' => 'JORDAN',
        'JP' => 'JAPAN',
        'KE' => 'KENYA',
        'KG' => 'KYRGYZSTAN',
        'KH' => 'CAMBODIA',
        'KI' => 'KIRIBATI',
        'KM' => 'COMOROS',
        'KN' => 'ST. KITTS',
        'KP' => 'KOREA, THE D.P.R OF (NORTH K.)',
        'KR' => 'KOREA, REPUBLIC OF (SOUTH K.)',
        'KV' => 'KOSOVO',
        'KW' => 'KUWAIT',
        'KY' => 'CAYMAN ISLANDS',
        'KZ' => 'KAZAKHSTAN',
        'LA' => 'LAO PEOPLES DEMOCRATIC REPUBLIC',
        'LB' => 'LEBANON',
        'LC' => 'ST. LUCIA',
        'LI' => 'LIECHTENSTEIN',
        'LK' => 'SRI LANKA',
        'LR' => 'LIBERIA',
        'LS' => 'LESOTHO',
        'LT' => 'LITHUANIA',
        'LU' => 'LUXEMBOURG',
        'LV' => 'LATVIA',
        'LY' => 'LIBYA',
        'MA' => 'MOROCCO',
        'MC' => 'MONACO',
        'MD' => 'MOLDOVA, REPUBLIC OF',
        'ME' => 'MONTENEGRO, REPUBLIC OF',
        'MG' => 'MADAGASCAR',
        'MH' => 'MARSHALL ISLANDS',
        'MK' => 'MACEDONIA, REPUBLIC OF',
        'ML' => 'MALI',
        'MM' => 'MYANMAR',
        'MN' => 'MONGOLIA',
        'MO' => 'MACAU',
        'MP' => 'COMMONWEALTH NO. MARIANA ISLANDS',
        'MQ' => 'MARTINIQUE',
        'MR' => 'MAURITANIA',
        'MS' => 'MONTSERRAT',
        'MT' => 'MALTA',
        'MU' => 'MAURITIUS',
        'MV' => 'MALDIVES',
        'MW' => 'MALAWI',
        'MX' => 'MEXICO',
        'MY' => 'MALAYSIA',
        'MZ' => 'MOZAMBIQUE',
        'NA' => 'NAMIBIA',
        'NC' => 'NEW CALEDONIA',
        'NE' => 'NIGER',
        'NG' => 'NIGERIA',
        'NI' => 'NICARAGUA',
        'NL' => 'NETHERLANDS, THE',
        'NO' => 'NORWAY',
        'NP' => 'NEPAL',
        'NR' => 'NAURU, REPUBLIC OF',
        'NU' => 'NIUE',
        'NZ' => 'NEW ZEALAND',
        'OM' => 'OMAN',
        'PA' => 'PANAMA',
        'PE' => 'PERU',
        'PF' => 'TAHITI',
        'PG' => 'PAPUA NEW GUINEA',
        'PH' => 'PHILIPPINES, THE',
        'PK' => 'PAKISTAN',
        'PL' => 'POLAND',
        'PR' => 'PUERTO RICO',
        'PT' => 'PORTUGAL',
        'PW' => 'PALAU',
        'PY' => 'PARAGUAY',
        'QA' => 'QATAR',
        'RE' => 'REUNION, ISLAND OF',
        'RO' => 'ROMANIA',
        'RS' => 'SERBIA, REPUBLIC OF',
        'RU' => 'RUSSIAN FEDERATION, THE',
        'RW' => 'RWANDA',
        'SA' => 'SAUDI ARABIA',
        'SB' => 'SOLOMON ISLANDS',
        'SC' => 'SEYCHELLES',
        'SD' => 'SUDAN',
        'SE' => 'SWEDEN',
        'SG' => 'SINGAPORE',
        'SH' => 'SAINT HELENA',
        'SI' => 'SLOVENIA',
        'SK' => 'SLOVAKIA',
        'SL' => 'SIERRA LEONE',
        'SM' => 'SAN MARINO',
        'SN' => 'SENEGAL',
        'SO' => 'SOMALIA',
        'SR' => 'SURINAME',
        'SS' => 'SOUTH SUDAN',
        'ST' => 'SAO TOME AND PRINCIPE',
        'SV' => 'EL SALVADOR',
        'SY' => 'SYRIA',
        'SZ' => 'SWAZILAND',
        'TC' => 'TURKS AND CAICOS ISLANDS',
        'TD' => 'CHAD',
        'TG' => 'TOGO',
        'TH' => 'THAILAND',
        'TJ' => 'TAJIKISTAN',
        'TL' => 'TIMOR LESTE',
        'TN' => 'TUNISIA',
        'TO' => 'TONGA',
        'TR' => 'TURKEY',
        'TT' => 'TRINIDAD AND TOBAGO',
        'TV' => 'TUVALU',
        'TW' => 'TAIWAN',
        'TZ' => 'TANZANIA',
        'UA' => 'UKRAINE',
        'UG' => 'UGANDA',
        'US' => 'UNITED STATES OF AMERICA',
        'UY' => 'URUGUAY',
        'UZ' => 'UZBEKISTAN',
        'VA' => 'VATICAN CITY STATE',
        'VC' => 'ST. VINCENT',
        'VE' => 'VENEZUELA',
        'VG' => 'VIRGIN ISLANDS (BRITISH)',
        'VI' => 'VIRGIN ISLANDS (US)',
        'VN' => 'VIETNAM',
        'VU' => 'VANUATU',
        'WS' => 'SAMOA',
        'XB' => 'BONAIRE',
        'XC' => 'CURACAO',
        'XE' => 'ST. EUSTATIUS',
        'XM' => 'ST. MAARTEN',
        'XN' => 'NEVIS',
        'XS' => 'SOMALILAND, REP OF (NORTH SOMALIA)',
        'XY' => 'ST. BARTHELEMY',
        'YE' => 'YEMEN, REPUBLIC OF',
        'YT' => 'MAYOTTE',
        'ZA' => 'SOUTH AFRICA',
        'ZM' => 'ZAMBIA',
        'ZW' => 'ZIMBABWE'
    ];

    static $reason_codes = [
        'Commercial'       => 'C',
        'Gift'             => 'G',
        'Sample'           => 'S',
        'Return'           => 'U',
        'Repair'           => 'R',
        'Personal Effects' => 'E',
        'Personal Use'     => 'E',
        'Documents'        => 'P',
        'Other'            => 'P'
    ];

}

?>